image: python:3.12

before_script:
  - pip install mkdocs mkdocs-material pymdown-extensions

pages:
  stage: deploy
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main